config/routes.rb
Txt2cookEngine::Application.routes.draw do
  resources :recipes

  root :to => "recipes#index"
end

app/models/phonenumber.rb
class Phonenumber < ActiveRecord::Base
  attr_accessible :phone_number
  validates :phone_number, presence: true, :numericality => true, :uniqueness => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	attr_accessible :recipe_name, :difficulty_level, :total_time, :ingredient_count
	validates :recipe_name, :difficulty_level, :total_time, :ingredient_count, presence: true
	validates :total_time,:ingredient_count, :numericality => {:only_integer => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phonenumber_controller.rb
class PhoneNumber < ApplicationController
	def new
		@phonenumber = PhoneNumber.new

		respond_to do |format|
			format.html
			format.json {render json: @phonenumber}
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
	  @recipes = Recipe.all

	  respond_to do |format|
		format.html
		format.json { render json: @recipes }
	  end
	end

	def show
	  @recipe = Recipe.find(params[:id])
    
	  respond_to do |format|
        format.html
        format.json { render json: @recipe }
      end
    end

    def new
      @recipe = Recipe.new

      respond_to do |format|
      	format.html
      	format.json { render json: @recipe }
      end
    end

    def edit
    	@recipe = Recipe.find(params[:id])
    end

    def create
      @recipe = Recipe.new(params[:recipe])

      respond_to do |format|
      	if @recipe.save
      		format.html {redirect_to @recipe, notice: 'You added #{recipe.recipe_name}!'}
      		format.json { render json: @recipe, status: :created, location: @recipe }
      	else
      		format.html {render action: "new"}
      		format.json { render json: @recipe.errors, status: :unprocessable_entity }
      	end
      end
    end

    def update
    	@recipe = Recipe.find(params[:id])

    	respond_to do |format|
    		if @recipe.update_attributes(params[:recipe])
    		   format.html {redirect_to @recipe, notice: 'Recipe successfully updated'}
    		   format.json {head :no_content}
    		else
    			format.html {render action: "edit"}
		        format.json { render json: @recipe.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
	    @recipe = Recipe.find(params[:id])
	    @recipe.destroy 

	    respond_to do |format|
	      format.html { redirect_to recipes_path }
	      format.json { head :no_content }
	    end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Txt2cookEngine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
	<% if @recipe.errors.any? %>
		<h2><%= pluralize(@recipe.errors.count, "error") %>
			stopped this recipe from saving: </h2>
		<ul>
			<% @recipe.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	<% end %>

  <form>
  	<fieldset>
  		<legend> Recipe info </legend>
  		<%= f.label :recipe_name %>
  		<%= f.text_field :recipe_name %>
  		<%= f.label :difficulty_level %>
  		<%= f.text_field :difficulty_level %>
  		<%= f.label :total_time %>
  		<%= f.text_field :total_time %>
  		  <%= f.label :ingredient_count %>
  		<%= f.text_field :ingredient_count %>
  		<%= f.submit :class => 'add_button' %>
  	</fieldset>

  </form>
<% end %>

app/views/recipes/edit.html.erb
<h1> Edit <%= @recipe.recipe_name %> </h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html>
	<head><title>Txt2Cook-Engine</title></head>
	<body>
		<h1> Recipe index</h1>
		<table>
			<tr>
				<th> Recipe Name</th>
				<th> Difficulty</th>
				<th> Time </th>
				<th> # Ingredients </th>
			</tr>
			<% @recipes.each do |recipe| %>
			<tr>			
				<td><%= recipe.recipe_name %></td>
				<td><%= recipe.difficulty_level %></td>
				<td><%= recipe.total_time %></td>
				<td><%= recipe.ingredient_count %></td>
				</tr>
			<% end %>
		</table>
	<body>
</html>

app/views/recipes/new.html.erb
<h1> Add a new recipe </h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
	<head><title>Txt2Cook-Engine</title></head>
	<body>
		<h1><%= @recipe.recipe_name %> </h1>
		<%= @recipe.ingredient_count %>
		<%= @recipe.total_time %>
		<%= @recipe.difficulty_level %>
		<%= link_to "recipe listing", recipes_path %>
		<%= link_to 'Edit recipe', edit_recipe_path(@recipe) %>
	</body>
</html>